# -*- coding: utf-8 -*-
"""Student_Management_System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14D5Sn2QZAakOiDgDTS__OmFv8EmrPqax

Student Management System

A simple Python console-based project
to manage student records.

Features:
- Add Student
- View Students
- Search Student
- Update Marks
- Delete Student
- Automatic Grade Calculation
"""

students = []

def calculate_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    else:
        return "F"

while True:
    print("\n--- STUDENT MANAGEMENT SYSTEM ---")
    print("1. Add Student")
    print("2. View All Students")
    print("3. Search Student")
    print("4. Update Student Marks")
    print("5. Delete Student")
    print("6. Exit")

    choice = input("Enter your choice (1-6): ")

    if choice == "1":
        roll_no = input("Enter Roll Number: ")
        if any(student["Roll No"] == roll_no for s in students):
            print("Student with this Roll Number already exists")
            continue
        name = input("Enter Name: ")
        department = input("Enter Department: ")
        try:
            marks = int(input("Enter Marks: "))
        except ValueError:
            print("Please enter valid numeric marks")
            continue

        grade = calculate_grade(marks)

        student = {
            "Roll No": roll_no,
            "Name": name,
            "Department": department,
            "Marks": marks,
            "Grade": grade
        }
        students.append(student)
        print("Student added successfully!")

    elif choice == "2":
        if not students:
            print("No students found")
        else:
            print("\n--- Student Records ---")
            for s in students:
                print(s)
    elif choice == "3":
        search_roll = input("Enter Roll Number to search: ")
        found = False
        for student in students:
            if s["Roll No"] == search_roll:
                print("Student Found:")
                print(student)
                found = True
                break
        if not found:
            print("Student not found")

    elif choice == "4":
        update_roll = input("Enter Roll Number to update marks: ")
        found = False
        for student in students:
            if student["Roll No"] == update_roll:
                new_marks = int(input("Enter new marks: "))
                student["Marks"] = new_marks
                student["Grade"] = calculate_grade(new_marks)
                print("Marks and grade updated successfully!")
                found = True
                break
        if not found:
            print("Student not found")

    elif choice == "5":
        delete_roll = input("Enter Roll Number to delete: ")
        found = False
        for student in students:
            if student["Roll No"] == delete_roll:
                students.remove(s)
                print("Student deleted successfully!")
                found = True
                break
        if not found:
            print("Student not found")
    elif choice == "6":
        print("Exiting Student Management System")
        break
    else:
        print("Invalid choice. Please select 1-6.")